apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: minio
  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-certificate: "ingress-alpha-root"
spec:
  ingressClassName: nginx
  rules:
    - host: vpo-minio.cloudteam.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9090
    - host: vpo-minios3.cloudteam.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
  tls:
    - hosts:
      - vpo-minio.cloudteam.vn
      secretName: minio-tls
    - hosts:
      - vpo-minios3.cloudteam.vn
      secretName: minio-tls
