apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  project: default
  source:
    path: deployment/argocd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        linkerd.io/inject: enabled
    syncOptions:    
      - CreateNamespace=false
      - Validate=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
