apiVersion: argoproj.io/v1alpha1
kind: Applications
metadata:
  name: ingress-controller
  namespace: argocd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-controller
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.5.2
    helm:
      values: |
        controller:
          admissionWebhooks:
            enabled: false
          podAnnotations:
            linkerd.io/inject: enabled    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
