apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo-minio
  project: default
  source:
    chart: minio
    repoURL: https://github.com/minio/minio
    targetRevision: 8.0.10
    helm:
      values: |
        replicas: 2
        size: 50Gi
        service:
          nodePort: 32111
        defaultBucket:
          enabled: true
        s3gateway:
          enabled: true
          replicas: 2
          serviceEndpoint: ""
          accessKey: "s3gateway"
          secretKey: "s3gateway"
    syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
