apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-staging
  namespace: default
spec:
  # Secret names are always required.
  secretName: ssl-cert-staging
  issuerRef:
    name: letsencrypt-staging
      kind: ClusterIssuer
    commondName: minio.cloudteam.work
    dnsName:
    - minio.cloudteam.work
