apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-prod
  namespace: default
spec:
  # Secret names are always required.
  secretName: ssl-cert-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commondName: 42.96.37.192.cloudteam.work
  dnsNames:
  - 42.96.37.192.cloudteam.work
