apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-prod
  namespace: default
spec:
  secretName: ssl-cert-prod
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 42.96.37.192.cloudteam.work
  dnsNames:
  - 42.96.37.192.cloudteam.work
